"""Add workout session and rep detection models

Revision ID: 95702332fd1d
Revises: 
Create Date: 2025-06-05 17:01:50.705987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95702332fd1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rep_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('avg_rep_duration', sa.Float(), nullable=False),
    sa.Column('min_rep_duration', sa.Float(), nullable=False),
    sa.Column('max_rep_duration', sa.Float(), nullable=False),
    sa.Column('avg_rest_between_reps', sa.Float(), nullable=False),
    sa.Column('motion_signature', sa.JSON(), nullable=True),
    sa.Column('training_session_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rep_patterns_device_id'), 'rep_patterns', ['device_id'], unique=False)
    op.create_index(op.f('ix_rep_patterns_id'), 'rep_patterns', ['id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps_per_set', sa.Integer(), nullable=True),
    sa.Column('current_set', sa.Integer(), nullable=True),
    sa.Column('current_reps', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'cancelled', name='workoutstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_device_id'), 'workout_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_table('rep_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('rep_number', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('rep_completed', 'set_completed', 'rest_started', 'form_warning', name='repeventtype'), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('motion_quality', sa.Float(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('rep_duration', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rep_events_device_id'), 'rep_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_rep_events_id'), 'rep_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rep_events_id'), table_name='rep_events')
    op.drop_index(op.f('ix_rep_events_device_id'), table_name='rep_events')
    op.drop_table('rep_events')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_device_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_rep_patterns_id'), table_name='rep_patterns')
    op.drop_index(op.f('ix_rep_patterns_device_id'), table_name='rep_patterns')
    op.drop_table('rep_patterns')
    # ### end Alembic commands ###
